import Image from "next/image";
import Link from "next/link";
import React from "react";
import { PiGreaterThanLight } from "react-icons/pi";

const BlogDetail = () => {
  return (
    <div>
      <div className="bg-[#1D285614] relative">
        <div className="flex items-center widthclass relative">
          <h1 className="text-black pl-16 pt-10 font-24 font-normal font-inter hidden sm:flex items-center gap-2 z-10">
            Metricwise
            <span className="paragraph font-20 font-normal font-inter opacity-50 flex items-center gap-2">
              <PiGreaterThanLight /> Resources <PiGreaterThanLight /> Blogs
              <PiGreaterThanLight /> Define Monitoring
            </span>
          </h1>

          <div className="absolute top-1 -left-1">
            <Image src="/hr1.png" width={138} height={138} alt="path-bg" />
          </div>
        </div>
        <div className="pt-20 pb-16 sm:pb-40 md:pb-64 lg:pb-96 relative widthclass px-10 xl:px-[165px] flex justify-center items-center flex-col">
          <div className="w-full text-left">
            <h1 className="font-36 font-bold lg:leading-10 mb-5 primaryblue z-10">
              Monitoring V/S Observability
            </h1>
          </div>
          <div className="absolute top-40 z-10 p-2 sm:p-10">
            <Image
              src="/blog-detail.svg"
              width={1110}
              height={541}
              alt="blog-detail"
            />
          </div>
        </div>

        <div className="absolute bottom-0">
          <Image src="/hr2.png" width={108} height={136} alt="path-bg" />
        </div>
      </div>

      <div className="sm:flex items-start gap-16 mt-32 sm:mt-56 md:mt-72 px-10 xl:px-20 2xl:px-[210px] container m-auto">
        <div className="flex flex-row sm:flex-col items-center gap-8 mb-10">
          <Image src="/facebook.svg" width={24} height={24} alt="social-icon" />
          <Image src="/twitter.svg" width={24} height={24} alt="social-icon" />
          <Image
            src="/instagram.svg"
            width={24}
            height={24}
            alt="social-icon"
          />
          <Image src="/github.svg" width={24} height={24} alt="social-icon" />
        </div>

        <div className="w-full">
          <div className="lg:flex justify-between items-center lg:px-5">
            <span className="inline-flex items-center rounded-md bg-[#2E2E2E33] px-2 py-1 text-black font-20 font-medium">
              Artificial Intelligence
            </span>
            <div className="text-gray-500 text-sm mt-3 lg:mt-0">
              <span className="primaryblue font-16 font-normal leading-5">
                July 29, 2024 . 4 Min Read
              </span>
            </div>
          </div>

          <div className="space-y-4 mt-10 lg:mt-16">
            <div className="font-16 font-normal leading-5 primaryblue">
              The terms monitoring and observability are prevalent in the field
              of AI/ML systems. Although they may initially appear similar,
              there are notable distinctions between the two concepts. This
              article explores the precise definitions and subtleties associated
              with AI/ML monitoring and observability, providing insights into
              their respective roles and significant importance in the current
              landscape of machine learning.
            </div>

            {/* monitoring */}

            <div className="space-y-4 mt-10 lg:mt-16">
              <h1 className="font-24 font-semibold leading-7 primaryblue">
                Defining Monitoring
              </h1>

              <div className="font-16 font-normal leading-5 primaryblue">
                Machine learning monitoring involves a continuous and systematic
                process for tracking the behavior and performance of a machine
                learning model across its developmental and deployment stages.
                This encompasses the aggregation, analysis, and interpretation
                of logs, metrics, and data generated by ML applications or
                models, ensuring optimal functionality and facilitating the
                timely detection of potential issues or anomalies.
              </div>

              <div>
                <h1 className="font-20 font-semibold leading-7 primaryblue">
                  Monitoring in machine learning involves identifying and
                  tracking various crucial elements, which <br /> include:
                </h1>

                <ul className="mt-8 border-l border-[#2E2E2E66] pl-7 space-y-5">
                  <li className="flex items-center gap-3">
                    <Image src="/tick.svg" width={24} height={24} alt="tick" />
                    Metrics like accuracy, precision , recall, and others.
                  </li>
                  <li className="flex items-center gap-3">
                    <Image src="/tick.svg" width={24} height={24} alt="tick" />
                    Observing concept, data, and model drift.
                  </li>
                  <li className="flex items-center gap-3">
                    <Image src="/tick.svg" width={24} height={24} alt="tick" />
                    Recognizing performance degradation in model performance.
                  </li>
                  <li className="flex items-center gap-3">
                    <Image src="/tick.svg" width={24} height={24} alt="tick" />
                    Addressing bias and fairness considerations in models.
                  </li>
                  <li className="flex items-center gap-3">
                    <Image src="/tick.svg" width={24} height={24} alt="tick" />
                    Identifying anomalies and outliers in model behavior or
                    data.
                  </li>
                  <li className="flex items-center gap-3">
                    <Image src="/tick.svg" width={24} height={24} alt="tick" />
                    Tracking model latency.
                  </li>
                  <li className="flex items-center gap-3">
                    <Image src="/tick.svg" width={24} height={24} alt="tick" />
                    Evaluating the utilization of computational resources,
                    memory, and other system resources.
                  </li>
                  <li className="flex items-center gap-3">
                    <Image src="/tick.svg" width={24} height={24} alt="tick" />
                    Detecting data quality issues in input datasets, such as
                    missing values or incorrect labels, <br /> which can
                    negatively impact model performance.
                  </li>
                  <li className="flex items-center gap-3">
                    <Image src="/tick.svg" width={24} height={24} alt="tick" />
                    Model versioning
                  </li>
                  <li className="flex items-center gap-3">
                    <Image src="/tick.svg" width={24} height={24} alt="tick" />
                    Identifying breaches and unauthorized access attempts.
                  </li>
                </ul>
              </div>

              <div className="space-y-7">
                <h1 className="font-20 font-semibold leading-7 primaryblue">
                  Monitoring in machine learning holds importance for various
                  reasons, including:
                </h1>
                <div className="font-16 font-bold leading-5 primaryblue">
                  Anomaly Detection and Resolution Strategy:
                  <span className="font-normal">
                    The early identification of anomalies through Machine
                    Learning (ML) monitoring empowers data science teams to
                    implement timely interventions, effectively mitigating
                    issues before they escalate. This proactive methodology is
                    instrumental in preventing significant business disruptions
                    and preempting customer dissatisfaction, particularly in
                    sectors with mission-critical operations.
                  </span>
                </div>

                <div className="font-16 font-bold leading-5 primaryblue">
                  Iterative Model Enhancement Framework:
                  <span className="font-normal">
                    ML Monitoring establishes a structured framework for
                    continual model improvement by providing detailed feedback
                    on model behavior. This iterative feedback loop facilitates
                    the ongoing refinement of ML algorithms and strategies,
                    resulting in continuous improvement and heightened model
                    performance over time.
                  </span>
                </div>

                <div className="font-16 font-bold leading-5 primaryblue">
                  Performance Validation in Production Environments:
                  <span className="font-normal">
                    Monitoring offers invaluable insights into model performance
                    within production environments, ensuring the consistent
                    delivery of reliable results in real-world applications. To
                    achieve this, monitoring employs a diverse array of
                    techniques, including cross-validation and A/B testing, to
                    facilitate the thorough assessment of model generalization
                    and competence in dynamic settings. Anomaly Detection and
                    Resolution Strategy: The early identification of anomalies
                    through Machine Learning (ML) monitoring empowers data
                    science teams to implement timely interventions, effectively
                    mitigating issues before they escalate. This proactive
                    methodology is instrumental in preventing significant
                    business disruptions and preempting customer
                    dissatisfaction, particularly in sectors with
                    mission-critical operations.
                  </span>
                </div>
              </div>
            </div>

            {/* observability */}

            <div className="space-y-4">
              <div>
                <h1 className="font-24 font-semibold leading-7 primaryblue">
                  Defining Observability
                </h1>
              </div>

              <div className="font-16 font-normal leading-5 primaryblue">
                Observability in Machine Learning is an essential discipline
                that provides detailed insights into the complexities of ML data
                pipelines and the overall health of the system. This approach
                involves a thorough understanding of decision-making processes,
                dynamics of data flow, and interactions within the ML pipeline.
                The escalating complexity of ML systems demands heightened
                observability, propelled by the intricate interplay of diverse
                components such as data pipelines, model notebooks, cloud
                configurations, containers, distributed systems, and
                microservices.
              </div>

              <div className="pt-2">
                <h1 className="font-20 font-semibold leading-7 primaryblue">
                  ML observability encompasses the identification and tracking
                  of various critical elements, <br /> including:
                </h1>

                <ul className="mt-8 border-l border-[#2E2E2E66] pl-7 space-y-5">
                  <li className="flex items-center gap-3">
                    <Image src="/tick.svg" width={24} height={24} alt="tick" />
                    Monitoring model behavior throughout training, inference,
                    and decision-making processes.
                  </li>
                  <li className="flex items-center gap-3">
                    <Image src="/tick.svg" width={24} height={24} alt="tick" />
                    Assessing feature importance and their contributions to
                    model predictions.
                  </li>
                  <li className="flex items-center gap-3">
                    <Image src="/tick.svg" width={24} height={24} alt="tick" />
                    Evaluating model explainability and interpretability.
                  </li>
                  <li className="flex items-center gap-3">
                    <Image src="/tick.svg" width={24} height={24} alt="tick" />
                    Detecting biases inherent in ML models.
                  </li>
                  <li className="flex items-center gap-3">
                    <Image src="/tick.svg" width={24} height={24} alt="tick" />
                    Identifying anomalies and outliers in model behavior or
                    data.
                  </li>
                  <li className="flex items-center gap-3">
                    <Image src="/tick.svg" width={24} height={24} alt="tick" />
                    Monitoring model, data, and concept drift over time.
                  </li>
                  <li className="flex items-center gap-3">
                    <Image src="/tick.svg" width={24} height={24} alt="tick" />
                    Evaluating the overall performance of the ML system,
                    including response times, latency, and throughput.
                  </li>
                  <li className="flex items-center gap-3">
                    <Image src="/tick.svg" width={24} height={24} alt="tick" />
                    Conducting model error analysis.
                  </li>
                  <li className="flex items-center gap-3">
                    <Image src="/tick.svg" width={24} height={24} alt="tick" />
                    Tracking model versions and assessing their performance
                    using production data.
                  </li>
                </ul>
              </div>

              <div className="space-y-7 pt-2">
                <h1 className="font-20 font-semibold leading-7 primaryblue">
                  ML observability holds a crucial position in the realm of ML
                  and AI, providing essential advantages <br /> such as:
                </h1>
                <div className="font-16 font-bold leading-5 primaryblue">
                  Iterative Enhancement:
                  <span className="font-normal">
                    Machine Learning Observability is a critical element for
                    continuous improvement, offering intricate insights into
                    model behavior. This facilitates not only algorithm
                    refinement but also enables seamless model updates,
                    contributing to the continual enhancement of predictive
                    capabilities.
                  </span>
                </div>

                <div className="font-16 font-bold leading-5 primaryblue">
                  Iterative Model Enhancement Framework:
                  <span className="font-normal">
                    ML Monitoring establishes a structured framework for
                    continual model improvement by providing detailed feedback
                    on model behavior. This iterative feedback loop facilitates
                    the ongoing refinement of ML algorithms and strategies,
                    resulting in continuous improvement and heightened model
                    performance over time.
                  </span>
                </div>
              </div>

              <div className="pt-2">
                <h1 className="font-24 font-semibold leading-7 primaryblue">
                  ML Observability for Compliance and Accountability in
                  Regulated Industries:
                </h1>
              </div>

              <div className="font-16 font-normal leading-5 primaryblue">
                In regulated industries, ML Observability emerges as an
                indispensable tool for upholding compliance with ethical and
                legal standards. A comprehensive understanding of model
                decisions and data usage ensures that models remain accountable
                and operate within the confines of regulatory boundaries.
              </div>
            </div>

            {/* closing */}

            <div className="space-y-4">
              <div className="pt-2">
                <h1 className="font-24 font-semibold leading-7 primaryblue">
                  Closing Remarks
                </h1>
              </div>

              <div className="font-16 font-normal leading-5 primaryblue">
                In conclusion, monitoring and observability stand as integral
                components within AI/ML systems. The real-time surveillance,
                tracking and alert mechanisms provided by monitoring contribute
                to the timely identification of potential issues.
                Simultaneously, observability offers a higher-level perspective,
                aiding stakeholders in understanding system behavior,
                pinpointing challenges, and optimizing model performance. The
                integration of observability allows organizations to achieve
                comprehensive visibility across their AI/ML systems, fostering
                reliability, explainability, and optimization. As the field of
                machine learning continues to evolve, the significance of
                monitoring and observability is increasingly emphasized, playing
                a pivotal role in ensuring the success of AI-driven
                applications.
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="bg-[#1D285614] mt-16 px-10 md:px-20 2xl:px-52 py-10">
        <div className="container m-auto">
          <div className="flex justify-start items-start flex-col gap-5 relative">
            <h1 className="font-24 font-bold leading-10">
              Recommended Articles
            </h1>
            <p className="font-20 font-normal leading-6 md:leading-8 opacity-60">
              Sit omnis id iusto aliquam. Similique labore dolore nihil
              cupiditate natus <br className="hidden lg:block"/> accusantium saepe omnis. Fuga quod aliquid
              perferendis natus laudantium <br className="hidden lg:block"/> alias aut assumenda. Est autem
              maxime.
            </p>

            <div className="absolute -top-8 -left-20">
              <Image src="/hr1.png" width={138} height={138} alt="path-bg" />
            </div>
          </div>

          <div className="flex justify-center items-center gap-10 mt-11">
            {/* Single Grid Container */}
            <div className="grid lg:grid-cols-2 gap-10">
              {/* First Card */}
              <div className="sm:flex bg-white shadow-[0_3px_15px_rgb(0,0,0,0.2)] gap-5 p-6 rounded-[20px]">
                {/* Image container */}
                <div className="w-[128px] h-[160px] mb-5 sm:mb-0 flex-shrink-0">
                  <Image
                    width={128}
                    height={160}
                    src="/other.png"
                    className="rounded-[20px] w-full h-full object-cover"
                    alt="img"
                  />
                </div>

                {/* Content Section */}
                <div className="flex flex-col justify-between flex-grow gap-2">
                  <div>
                    <h3 className="text-[20px] font-inter font-semibold leading-6">
                      Insecure Output Handling
                    </h3>
                    <p className="text-[16px] font-inter font-normal leading-5 mt-3 opacity-[60%]">
                      Insecure output handling occurs when an application
                      indiscriminately accepts output from a Large Language
                      Model (LLM) without proper scrutiny.
                    </p>
                  </div>
                  <Link
                    href="/recourses/Blog/blog-detail"
                    className="primary-small-btn"
                  >
                    Learn more
                  </Link>
                </div>
              </div>

              {/* Second Card */}
              <div className="sm:flex bg-white shadow-[0_3px_15px_rgb(0,0,0,0.2)] gap-5 p-6 rounded-[20px]">
                {/* Image container */}
                <div className="w-[128px] h-[160px] mb-5 sm:mb-0 flex-shrink-0">
                  <Image
                    width={128}
                    height={160}
                    src="/other.png"
                    className="rounded-[20px] w-full h-full object-cover"
                    alt="img"
                  />
                </div>

                {/* Content Section */}
                <div className="flex flex-col justify-between flex-grow gap-2">
                  <div>
                    <h3 className="text-[20px] font-inter font-semibold leading-6">
                      Insecure Output Handling
                    </h3>
                    <p className="text-[16px] font-inter font-normal leading-5 mt-3 opacity-[60%]">
                      Insecure output handling occurs when an application
                      indiscriminately accepts output from a Large Language
                      Model (LLM) without proper scrutiny.
                    </p>
                  </div>
                  <Link
                    href="/recourses/Blog/blog-detail"
                    className="primary-small-btn"
                  >
                    Learn more
                  </Link>
                </div>
              </div>
            </div>
          </div>

          <div className="flex justify-end items-end mt-12">
            <Link href="/recourses/Blog" className="hero-btn">
              See More
              <Image src="/free.png" width={24} height={24} alt="free" />
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BlogDetail;
